import NavigationBar from "../components/navbar/navbar";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />

        {children}
        <footer>
          <h1 className="flex justify-center">footer</h1>
        </footer>
      </body>
    </html>
  );
}
